### ISSUE TITLE
Mistral on Docker - ERROR (app) Failed to find action [action_name=ansible]

### ISSUE THREAD

**Issue by khandhedia** [d0ugal/mistral-ansible-actions#15]
I cloned [this ](https://github.com/d0ugal/mistral-ansible-actions) GIT repository on mistral docker container at /opt/stack/mistral/mistral/actions/**testAction/** and executed below steps as mentioned in readme. However, it ended with `ERROR (app) Failed to find action [action_name=ansible]`.

Here is the step by step execution results:

**Step 1:**

root@a409562fb1fe:/opt/stack/mistral/mistral/actions/testAction/mistral-ansible-actions# **pip install mistral-ansible-actions**

```
Collecting mistral-ansible-actions
  Downloading mistral-ansible-actions-0.2.2.tar.gz
Building wheels for collected packages: mistral-ansible-actions
  Running setup.py bdist_wheel for mistral-ansible-actions ... done
  Stored in directory: /root/.cache/pip/wheels/33/81/4c/6877af65630e095b5fc707f9b99c1aee41183a9bf43052f9e5
Successfully built mistral-ansible-actions
Installing collected packages: mistral-ansible-actions
Successfully installed mistral-ansible-actions-0.2.2
```

root@a409562fb1fe:/opt/stack/mistral/mistral/actions/testAction/mistral-ansible-actions# **sudo mistral-db-manage populate**

```
2017-06-16 04:15:28.479 241 INFO mistral.db.sqlalchemy.migration.cli [-] populating db
2017-06-16 04:15:28.528 241 CRITICAL Mistral [-] Unhandled error: DBNonExistentTable: (sqlite3.OperationalError) no such table: action_definitions_v2 [SQL: u'DELETE FROM action_definitions_v2 WHERE (action_definitions_v2.project_id = ? OR action_definitions_v2.scope = ?) AND action_definitions_v2.is_system = 1'] [parameters: ('<default-project>', 'public')]
2017-06-16 04:15:28.528 241 ERROR Mistral Traceback (most recent call last):
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/bin/mistral-db-manage", line 10, in <module>
2017-06-16 04:15:28.528 241 ERROR Mistral     sys.exit(main())
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/sqlalchemy/migration/cli.py", line 137, in main
2017-06-16 04:15:28.528 241 ERROR Mistral     CONF.command.func(config, CONF.command.name)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/sqlalchemy/migration/cli.py", line 75, in do_populate
2017-06-16 04:15:28.528 241 ERROR Mistral     action_manager.sync_db()
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/services/action_manager.py", line 81, in sync_db
2017-06-16 04:15:28.528 241 ERROR Mistral     _clear_system_action_db()
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/services/action_manager.py", line 76, in _clear_system_action_db
2017-06-16 04:15:28.528 241 ERROR Mistral     db_api.delete_action_definitions(is_system=True)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/v2/api.py", line 205, in delete_action_definitions
2017-06-16 04:15:28.528 241 ERROR Mistral     return IMPL.delete_action_definitions(**kwargs)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/sqlalchemy/base.py", line 117, in _within_session
2017-06-16 04:15:28.528 241 ERROR Mistral     result = func(*args, **kw)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/v2/sqlalchemy/api.py", line 657, in delete_action_definitions
2017-06-16 04:15:28.528 241 ERROR Mistral     return _delete_all(models.ActionDefinition, **kwargs)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/mistral/db/v2/sqlalchemy/api.py", line 202, in _delete_all
2017-06-16 04:15:28.528 241 ERROR Mistral     _secure_query(model).filter_by(**kwargs).delete(synchronize_session=False)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3212, in delete
2017-06-16 04:15:28.528 241 ERROR Mistral     delete_op.exec_()
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1179, in exec_
2017-06-16 04:15:28.528 241 ERROR Mistral     self._do_exec()
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1363, in _do_exec
2017-06-16 04:15:28.528 241 ERROR Mistral     mapper=self.mapper)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1139, in execute
2017-06-16 04:15:28.528 241 ERROR Mistral     bind, close_with_result=True).execute(clause, params or {})
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
2017-06-16 04:15:28.528 241 ERROR Mistral     return meth(self, multiparams, params)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
2017-06-16 04:15:28.528 241 ERROR Mistral     return connection._execute_clauseelement(self, multiparams, params)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
2017-06-16 04:15:28.528 241 ERROR Mistral     compiled_sql, distilled_params
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
2017-06-16 04:15:28.528 241 ERROR Mistral     context)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1398, in _handle_dbapi_exception
2017-06-16 04:15:28.528 241 ERROR Mistral     util.raise_from_cause(newraise, exc_info)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
2017-06-16 04:15:28.528 241 ERROR Mistral     reraise(type(exception), exception, tb=exc_tb, cause=cause)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
2017-06-16 04:15:28.528 241 ERROR Mistral     context)
2017-06-16 04:15:28.528 241 ERROR Mistral   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 470, in do_execute
2017-06-16 04:15:28.528 241 ERROR Mistral     cursor.execute(statement, parameters)
2017-06-16 04:15:28.528 241 ERROR Mistral DBNonExistentTable: (sqlite3.OperationalError) no such table: action_definitions_v2 [SQL: u'DELETE FROM action_definitions_v2 WHERE (action_definitions_v2.project_id = ? OR action_definitions_v2.scope = ?) AND action_definitions_v2.is_system = 1'] [parameters: ('<default-project>', 'public')]
2017-06-16 04:15:28.528 241 ERROR Mistral

```
**Step 3:**

root@a409562fb1fe:/opt/stack/mistral/mistral/actions/testAction/mistral-ansible-actions# **mistral run-action ansible**

**Comment by vaibhavpatil123** [comment]
https://gist.github.com/vaibhavpatil123/d58c313becce52ac71eb4738da838640
